#pragma once

struct Player;
struct Galaxy;
struct Technology;
struct Module;
struct Weapon;
struct ShipHull;
struct ShipDesign;
struct Ship;
struct Fleet;
struct SectorObject;
struct Star;
struct InhabitableObject;
struct Sector;
struct Building;
struct PlanetaryFeatures;
struct Colony;
struct Planet;
struct SpaceBase;
