name: Auto Assign to Project(s)

on:
  issues:
    types: [opened, labeled]
  pull_request:
    types: [opened, labeled]
  issue_comment:
    types: [created]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Assign new issues to project
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: |
        github.event_name == 'issues' &&
        (
          github.event.action == 'opened' ||
          contains(github.event.issue.labels.*.name, 'mylabel')
        )
      with:
        project: 'https://github.com/srggrs/assign-one-project-github-action/projects/3'
        column_name: 'TODO'
